name: Deploy to Tinkerhost

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Deploy Theme
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr --delete
          path: ./wp-content/themes/eric-theme/
          remote_path: /htdocs/wp-content/themes/eric-theme/
          remote_host: ftpupload.net
          remote_user: ${{ secrets.FTP_USERNAME }}
          remote_key: ${{ secrets.FTP_PASSWORD }}
          
      - name: Deploy Plugin
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr --delete
          path: ./wp-content/plugins/eric-portfolio-projects/
          remote_path: /htdocs/wp-content/plugins/eric-portfolio-projects/
          remote_host: ftpupload.net
          remote_user: ${{ secrets.FTP_USERNAME }}
          remote_key: ${{ secrets.FTP_PASSWORD }}